config/routes.rb
LGBTHomelessness::Application.routes.draw do

  root 'home#index'
  get 'about' => "home#about"
  get 'who_are_you' => "home#who"
  get 'volunteer' => "home#volunteer"
  get 'contact' => "home#contact"
  get 'calendar' => "home#calendar"
  get 'results' => "home#result"
  post 'contact' => "contact#create"
  post 'volunteer' => 'volunteer#create'
  get 'volunteers' => "volunteer#index"
  get 'org_list' => "home#org_list"
  get 'wish_lists' => "home#wish_lists"
  get 'donate_money' => "home#donate_money"
  get 'give_help' => "home#give_help"
  get 'mobile' => "home#mobile"
  post 'sms_request' => "sms#received"
  get  'sms_test'    => "sms#test"

  resources :organizations do
      resources :programs
  end

  resources :programs

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application_mobile", :only => [ :mobile ]
  def index

  end

  def about

  end

  def who

  end

  def volunteer

  end

  def calendar
  end

  def results
    @programs = Program.all()
  end

  def contact

  end

  def mobile
    render 'mobile_index'
  end

  def org_list
    
  end 

  def wish_lists

  end

  def donate_money

  end

  def give_help

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="main col-lg-12">
	<h1><%= content_for(:title, "About") %>About</h1>

	<p>At the <A HREF="http://chicagosummit.lgbthomelessness.org/">Chicago Summit on LGBT Youth Homelessness</a> in May 2014, community organizers realized the need for a website connecting LGBT homeless youth with resources already available to them.</p>

        <blockquote class="youth-quote">“We don’t even know what’s available to us.” - Homeless Youth</blockquote>

	<p>From May 31 - June 1 at 2014's <A HREF="http://hackforchange.org/">National Day of Civic Hacking</a>, held at Chicago's <A HREF="http://www.adlerplanetarium.org/">Adler Planetarium</a>, 5 people formed a team to create this website. <a href="http://twitter.com/alison985" alt="Follow @alison985 on Twitter!">Alison</a>, <a href="http://twitter.com/nugentcodes" alt="Follow @nugentcodes on Twitter!">Janna</a>, <a href"http://twitter.com/d_chan42" alt="Follow @d_chan42 on Twitter!"> Kelsey</a>, <a href="http://twitter.com/laurendorman" alt="Follow @LaurenDorman on Twitter!">Lauren</a>, and <a href="http://twitter.com/stuart_lynn" alt="Follow @stuart_lynn on Twitter!">Stuart</a> hacked this site together in order to help LGBT homeless youth find resources.</p>

	<p>Follow us on Twitter at <a href="http://twitter.com/lgbtqhomeless" alt="Follow @LGBTQHomeless on Twitter!">@LGBTQHomeless</a>.
</div>

app/views/home/calendar.html.erb
<div class="main col-lg-12">
	<h1><%= content_for(:title, "Public Services Calendar") %>Public Services Calendar</h1>

	<p>We've placed all services with specific hours (except for housing and internet access) on a Google Calendar. You can add it to your Google Calendar account or calendar software of your choice with any of the following methods.</br>
		</br>Calendar ID: b9ack0te8p7l0rsa0j1ddvmp6g@group.calendar.google.com
		</br><A HREF="http://www.google.com/calendar/feeds/b9ack0te8p7l0rsa0j1ddvmp6g%40group.calendar.google.com/public/basic">Open in XML</a>
		</br><A HREF="http://www.google.com/calendar/ical/b9ack0te8p7l0rsa0j1ddvmp6g%40group.calendar.google.com/public/basic.ics">Open in iCal</a>
	</p>
</div>

app/views/home/contact.html.erb
 <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
 </section>

 <% if params[:flag_inaccurate_org] %>
    <div class="main col-lg-12">
        <h1>Inaccurate Information Report</h1>
        Please include what Organization has inaccurate information and what is inaccurate about it in the form below. You must click Submit to complete your report.<br /><br />
<% elsif params[:flag_inaccurate_prog] %>
    <div class="main col-lg-12">
        <h1>Inaccurate Information Report</h1>
        Please include what program has inaccurate information and what is inaccurate about it in the form below. You must click Submit to complete your report.<BR /><br />
<% else %>
    <h1><%= content_for(:title, "Contact Us") %>Contact Us</h1>
     <div class="main col-lg-12">
<% end %>


		<form action="/contact" method="post">
            <fieldset>
            	<label name="name">Name<span class="required"> *</span></label>
                <input type="text" id="name" name="name" required="true" class="contact input-block-level" placeholder="Name">
                <label name="email">Email<span class="required"> *</span></label>
                <input type="text" id="email" name="email" required="true" class="contact input-block-level" placeholder="Email">
                <label name="message">Your Message<span class="required"> *</span></label>
                <textarea rows="3" id="message" name="message" required="true" class="contact input-block-level" placeholder="Message"></textarea>
                <button type="submit" class="contact-button">Submit</button>
            </fieldset>
            <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
        </form>
</div>

app/views/home/donate_money.html.erb
<div class="main col-lg-12">
	<h1><%= content_for(:title, "Donate Money") %>Donate Money</h1>

	<table>
		<TR valign="top">
			<TD width="80%"><h3>Broadway Youth Center - (BYC, an HBHC program)</h3>
				A safe and affirming space for youth of all gender expressions & identities ages 12-24. They have drop-in, free HIV/STI testing, educational programs & resources.
			<TD width="20%"><A HREF="https://howardbrown1165.thankyou4caring.org/broadway-youth-center-donation-page">
				<%= image_tag("Donate-Button.png", :class => "logo", :alt => "Donate Now", :title => "Donate Now") %></a>
		</tr>
		<TR>
			<TD>
		</tr>
		<TR valign="top">
			<td><h3>The Night Ministry - The Crib</h3>
				An emergency overnight shelter that accepts 20 youth from 18-24 each night, 365 days a year from 9pm to 9am.
				<ul>
					<LI>A $50 donation provides a night of shelter for a young person at The Crib.  
					<LI>$20 helps purchase a three-day transit pass for youth to use when they look for jobs or attend medical or counseling appointments. 
					<LI>$10 provides one night of meals for a young person at The Crib. 
				</ul>
			<td><A HREF="https://thenightministry.ejoinme.org/MyPages/TheCrib/tabid/534715/Default.aspx"><%= image_tag("Donate-Button.png", :class => "logo", :alt => "Donate Now", :title => "Donate Now") %></a>
		</tr>
		<TR>
			<TD>
		</tr>
		<TR valign="top">
			<TD><h3>Lakeview Presbyterian Church - Cafe Pride</h3>
				Cafe Pride’s mission is to provide safe social space for LGBTQA young people on Friday nights from 8:00 – Midnight! Youth from all over the Chicagoland area come to be accepted as they are, to play cards, watch a movie, or just hang out! This program is 100% volunteer-run by members of the LVPC community. Volunteer opportunities are always available!
			<TD><A HREF="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9SXH9UVZVPAQ2"><%= image_tag("Donate-Button.png", :class => "logo", :alt => "Donate Now", :title => "Donate Now") %></a>
		</tr>
		<TR>
			<TD>
		</tr>
		<TR valign="top">
			<TD><h3>Broadway United Methodist Church - Youth Lounge</h3>
				A bi-monthly safe space for resilient Chicago youth. 
			<TD>Donate via checks mailed to:<BR>
				Broadway United Methodist Chuch<BR>
				c/o Youth Lounge<BR>
				3338 N Broadway St<BR>
				Chicago, IL 60657
		</tr>
		<TR>
			<TD>
		</tr>
		<TR valign="top">
			<TD><h3>Chicago House</h3>
				Chicago House and Social Service agency serves individuals and families who are disenfranchised by HIV/AIDS, LGBTQ marginalization, poverty, homelessness, and/or gender nonconformity by providing housing, employment services, medical linkage and retention services, HIV prevention services, legal services and other supportive programs.
			<TD><A HREF="https://donatenow.networkforgood.org/chicagohouse"><%= image_tag("Donate-Button.png", :class => "logo", :alt => "Donate Now", :title => "Donate Now") %></a>
		</tr>
		<TR>
			<TD>
		</tr>
		<TR valign="top">
			<TD><h3>Howard Brown Health Center</h3>
				Howard Brown Health Center exists to eliminate the disparities in health care experienced by lesbian, gay, bisexual and transgender people through research, education and the provision of services that promote health and wellness.
			<TD><A HREF="https://howardbrown1165.thankyou4caring.org/sslpage.aspx?pid=298"><%= image_tag("Donate-Button.png", :class => "logo", :alt => "Donate Now", :title => "Donate Now") %></a>
		</tr>

	</table>
	
</div>

app/views/home/give_help.html.erb
<div class="main col-lg-12">
	<h1><%= content_for(:title, "Give Help") %>Give Help</h1>

	<h3><%= link_to "Volunteer", volunteer_path %></h3>
	<h3><%= link_to "Wish List Items", wish_lists_path %></h3>
	<h3><%= link_to "Donate Money", donate_money_path %></h3>
</div>

app/views/home/index.html.erb
 <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
 </section>

 <div class="col-lg-12 jumbotron">
	<h1><%= content_for(:title, "Resources for LGBT Homeless Youth") %>Resources for LGBT Homeless Youth</h1>
</div>

<div class="col-lg-6">
  <button class="call-to-service"><%= link_to "I need help", who_are_you_path %></button>
</div>
<div class="col-lg-6">
  <button class="call-to-service"><%= link_to "I want to help", volunteer_path %></button>
</div>

<div class="col-lg-12">
	<h3 class="serving">Serving Chicago area LGBT youth.</h3>
</div>

<div class="col-lg-12">
	<!-- Begin MailChimp Signup Form -->
	<div class="mailchimp">
	<h4 class="subscribe">Subscribe to our supporter mailing list</h4>
	<div id="mc_embed_signup">
	<form action="http://lgbthomelessness.us8.list-manage1.com/subscribe/post?u=78316305daef30d40b00afba9&amp;id=fc129acb37" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank" novalidate>
	        <label for="mce-EMAIL">Email Address  <span class="required">*</span>
	</label></br>
	<div class="form-group">
	        <input type="email" value="" name="EMAIL" class="required email input-block-level input-lg form-control" id="mce-EMAIL">
	    </div>
	    <div class="form-group">
	        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="subscribe-button form-control">
	    </div>
	</form>

		        <div id="mce-responses" class="clear">
	                <div class="response" id="mce-error-response" style="display:none"></div>
	                <div class="response" id="mce-success-response" style="display:none"></div>
	        </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;"><input type="text" name="b_78316305daef30d40b00afba9_fc129acb37" tabindex="-1" value=""></div>
	</div>
	</div>
	<!--End mc_embed_signup-->
</div>

app/views/home/mobile_index.html.erb
 <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
 </section>

<div class="col-lg-6">
  <div class="jumbotron_mobile">
  <span class='h1-mobile'>
  	Need a hand?<BR />
  	You are not alone.
	</span>
  </div>
  <div class="rainbow">
    <span class='red'>&nbsp;</span>
    <span class='orange'>&nbsp;</span>
    <span class='yellow'>&nbsp;</span>
    <span class='blue'>&nbsp;</span>
    <span class='green'>&nbsp;</span>
    <span class='purple'>&nbsp;</span>
  </div>
  <div class="jumbotron_mobile stat-color">
  	<span class="stat-div"><h3>40%</h3> 
  	  <span class="stat-comment">
        of homeless youth<br />
  	  	identify as LGBT.
      </span>
    </span>
  </div>
  <div class="rainbow">
    <span class='red'>&nbsp;</span>
    <span class='orange'>&nbsp;</span>
    <span class='yellow'>&nbsp;</span>
    <span class='blue'>&nbsp;</span>
    <span class='green'>&nbsp;</span>
    <span class='purple'>&nbsp;</span>
  </div>
  <div class="jumbotron_mobile blue-container">
  <span class='blue-container'>
  	Find resources to connect with
  	the love and support you need.
  </span>
  <br /><br />
  <%= image_tag("icons.png", :alt => "icons",
                :title => "icons", :width => 320, :height => 67) %>
  <BR /></br />
  </div>
  <span class='white-container'>
  	<span class='triangle-mobile'><center>  <%= image_tag("bluegreen-triangle.png", :alt => "triangle",
                :title => "triangle", :width => 49, :height => 33) %> </center></span>
  <span class='mobile-blue-txt'>WE HAVE HUNDREDS OF RESOURCES</span><Br />
  Tell us more about you so we<br />
  can narrow down the options.
  </span>
</div>


	<form method='get' action='/organizations' style='padding: 3px;'>
<span class='gray-container'>
	<p>1. What service do you need?<span class="required"> *</span></p>
<select required='true' name="service" id="service">
<option selected="selected" disabled="disabled" value="">Select a service</option>
		<option value="housing">Shelter</option>
		<option value="drop-in">Drop-In</option>
		<option value="food">Food</option>
		<option value="hotline">Hotlines</option>
		<option value="health">Health</option>
		<option value="Counseling">Counseling</option>
		<option value="legal">Legal</option>
		<option value="domestic violence">Domestic Violence</option>
		<option value="education">Education</option>
		<option value="employment">Empolyment</option>
		<option value="arts">Art</option>
		<option value="activism">Activism</option>
		<option value="internet access">Internet Access</option>
		</select>
</span>
<span class='white-container'>
<p>2. Where are you located?<span class="required"> *</span></p>
<select required='true' name="city" id="city">
<option selected="selected" disabled="disabled" value="">Select a metro area</option>
		<option value="Chicago">Chicago</option>
		<option value="Los Angeles">Los Angeles</option>
		</select>
</span>
<span class='gray-container'>
<P>3. Are you homeless or unstably housed?</p>
		<input type="radio" name="homeless" value="yes"> Yes<br />
		<input type="radio" name="homeless" value="no"> No<br /><br />
		<small>We will provide you resources either way.</small>
</span>
<span class='white-container'>
<p>4. How old are you?<span class="required"> *</span></p>
		<!--<small>We only require age to make sure we don’t show you a program you aren’t eligible for, however additional information can help refine your search further.</small>
	--></p>
		<select required='true' name="age" id="age">
		<option selected="selected" disabled="disabled" value="">Select your age</option>
		<option value="13">13</option>
		<option value="14">14</option>
		<option value="15">15</option>
		<option value="16">16</option>
		<option value="17">17</option>
		<option value="18">18</option>
		<option value="19">19</option>
		<option value="20">20</option>
		<option value="21">21</option>
		<option value="22">22</option>
		<option value="23">23</option>
		<option value="24">24</option>
		<option value="25">25</option>
		<option value="26">26+</option>
		</select>
</span>
	<!--<p>What is your sexual orientation?</p>
	<select name="orientation" id="sexualOrientation">
	        <option selected="selected">Select your orientation</option>
		<option value="gay">Gay</option>
		<option value="lesbian">Lesbian</option>
		<option value="bisexual">Bisexual</option>
		<option value="straight">Straight</option>
	</select>

	<p>What gender do you identify as?</p>
	<select name="sex" id="sex">
	        <option selected="selected">Select your gender</option>
		<option value="Male">Male</option>
		<option value="Female">Female</option>
	</select>-->
<span class='gray-container'>
<P>5. How do you identify? (Check all that apply)</p>
		<input type="checkbox" name="lesbian"> Lesbian<br/>
		<input type="checkbox" name="gay"> Gay<br/>
		<input type="checkbox" name="bisexual"> Bisexual<br/>
		<input type="checkbox" name="Straight"> Straight/Heterosexual<br/>
		<input type="checkbox" name="asexual"> Asexual<br/>
		<input type="checkbox" name="Questioning"> Questioning my sexual orientation<br/>
		<input type="checkbox" name="SOnotlisted"> Sexual Orientation Not Listed: <input type="text" name="SOother" ><br/>
		<input type="checkbox" name="female"> Female <br/>
		<input type="checkbox" name="male"> Male <br/>
		<input type="checkbox" name="transfemale"> Trans Female <br/>
		<input type="checkbox" name="transmale"> Trans Male<br/>
		<input type="checkbox" name="Cisgenderd"> Cisgendered<br/>
		<input type="checkbox" name="GNC"> Gender Non-Conforming<br/>
		<input type="checkbox" name="Gendernotlisted"> Gender Not Listed: <input type="text" name="Genderother">
		<br /><br />
</span>
<span class='white-container'>
<P>6. What is your race/ethnicity? (Check all that apply)</p>
		<p>
		<input type="checkbox" name="afam"> African-American<br/>
		<input type="checkbox" name="white"> Caucasian / White<br/>
		<input type="checkbox" name="hispanic"> Hispanic / Latino<br/>
		<input type="checkbox" name="asian"> Asian <br/>
		<input type="checkbox" name="nativehawaii"> Native Hawaiian or Other Pacific Islander <br/>
		<input type="checkbox" name="naam"> American Indian / Native American or Alaska Native <br/>
		<input type="checkbox" name="multiracial"> Multi-racial<br/>
		<input type="checkbox" name="racenotlisted"> Race/Ethnicity Not Listed: <input type="text" name="raceOther">
		</p>
</span>
<span class='gray-container'>
<p>7. Programas en Español sólo?</p>

	<div class="radio">
	    <input type="radio" name="spanish" id="optionYes" value="Y">
	    Yes</br>
	    <input type="radio" name="spanish" id="optionNo" value="N" checked>
	    No<br/>
	    <small>
	    	Do you need Spanish-speaking services?
	    </small>
	</div>
</span>
<p>
	<button class="resources-button">Submit</button>
	</form>

	<ul>
		<LI><%= link_to "About", about_path %></li>
		<LI><%= link_to "Contact Us", contact_path %></li>
		<li><%= link_to "Give Help", give_help_path %></li>
		<li><%= link_to "Services Calendar", calendar_path %></li>
		<LI><a href="http://twitter.com/lgbtqhomeless" alt="Follow @LGBTQHomeless on Twitter!">
          <%= image_tag("twitter-icon.png", :alt => "Follow @LGBTQHomeless on Twitter",
                :title => "@LGBTQHomeless", :width => 51, :height => 51) %> </a>
	</ul>

<div class="col-lg-12">
	<!-- Begin MailChimp Signup Form -->
	<div class="mailchimp">
	<h4 class="subscribe">Subscribe to our supporter mailing list</h4>
	<div id="mc_embed_signup">
	<form action="http://lgbthomelessness.us8.list-manage1.com/subscribe/post?u=78316305daef30d40b00afba9&amp;id=fc129acb37" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank" novalidate>
	        <label for="mce-EMAIL">Email Address  <span class="required">*</span>
	</label></br>
	<div class="form-group">
	        <input type="email" value="" name="EMAIL" class="required email input-block-level input-lg form-control" id="mce-EMAIL">
	    </div>
	    <div class="form-group">
	        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="submit-style form-control">
	    </div>
	    <div >
	    	The search results will provide a map based <br />
			on your internet browser location.
	    </div>
	</form>

		        <div id="mce-responses" class="clear">
	                <div class="response" id="mce-error-response" style="display:none"></div>
	                <div class="response" id="mce-success-response" style="display:none"></div>
	        </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;"><input type="text" name="b_78316305daef30d40b00afba9_fc129acb37" tabindex="-1" value=""></div>
	</div>
	</div>
	<!--End mc_embed_signup-->
</div>

app/views/home/org_list.html.erb
<div class="main col-lg-12">

      <ul class='list-group results'>
        <% Organization.all.each do |organization| %>

          <li class='list-group-item place sortable' >
            <%= link_to organization.name, organization %>

            <span class="friendliness">
                <% organization.friendliness_ratings.each do |rating|%>
                  <% if rating == "LGBT Focused" %>
                    <%= image_tag("lgbt_focused.png", :alt => "LGBT Focused", :title => "LGBT Focused") %>
                  <%end%>
                  <% if rating == "LGBT Friendly" %>
                    <%= image_tag("lgbt_friendly.png", :alt => "LGBT Friendly", :title => "LGBT Friendly") %>
                  <%end%>
                <%end%>
            </span>

            <span class="badge"><%=organization.programs.count%></span>

          </li>
        <%end%>
      </ul>
</div>

app/views/home/results.html.erb
<h1><%= content_for(:title, "Your Results") %></h1>

app/views/home/volunteer.html.erb
<div class="main col-lg-12">
	<h1><%= content_for(:title, "How can we help you?") %>I Want to Help LGBT Homeless Youth</h1>

	<p>Fill out the form below to indicate an interest in helping LGBT Homeless Youth. I will work to match you up with a volunteer opportunity.</p>

	<form action="/volunteer" method="post">
		<label name="firstName">First Name<span class="required"> *</label>
		<input type="text" id="firstName" name="first_name" class="volunteer input-block-level" required="true"  placeholder="First Name">
		 
		<label name="firstName">Last Name</label>
		<input type="text" id="lastName" name="last_name" class="volunteer input-block-level" placeholder="Last Name">
		 
		<label name="email">Email<span class="required"> *</required></label>
		<input type="text" id="email" name="email" required="true" class="volunteer input-block-level" placeholder="Email">
		 
		<p>Announcements?</p>
		<input type="radio" name="announcements" value="Y" checked>
		Yes, send me announcements related to LGBT Youth Homelessness</br>
		<input type="radio" name="announcements" value="N">
		No, don't send me announcements - just let me know how I can get involved.</br></br>
		<label name="location">Your Location<span class="required"> *</span></br>
		<small>(i.e. Chicago, IL - North Side)</small></label>
		<input type="text" name="location" class="volunteer input-block-level" placeholder="Location">
		 
		<p>Would you be comfortable volunteering for a program that requires:</p>
		 <input type="checkbox" name="programRequirements_group[]" value="a background check"> a background check</br>
		 <input type="checkbox" name="programRequirements_group[]" value="a tuberculosis screening"> a tuberculosis screening</br>
		 <input type="checkbox" name="programRequirements_group[]" value="lifting up to 50 pounds"> lifting up to 50 pounds</br>
		 <input type="checkbox" name="programRequirements_group[]" value="working in an LGBT-affirming church setting"> working in an LGBT-affirming church setting</br></br>

		<p>Your Age Range<span class="required"> *</span></p>
		 <select name="age" id="age">
		 <option value="Under 18">Under 18</option>
		 <option value="18-25">18-25</option>
		 <option value="26+">26+</option>
		 </select>

		<p>Specific Skills/Abilities</p>
		 <input type="checkbox" name="skills_group[]" value="Food Preparation"> Food Preparation</br>
		 <input type="checkbox" name="skills_group[]" value="Legal/Lawyer"> Legal/Lawyer</br>
		 <input type="checkbox" name="skills_group[]" value="Doctor/Medical/Nurse"> Medical/Doctor/Nurse</br>
		 <input type="checkbox" name="skills_group[]" value="Counselors/Mental Health Workers"> Counselors/Mental Health Workers</br>
		 <input type="checkbox" name="skills_group[]" value="HIV/STI Testing Counselor"> HIV/STI Testing Counselor</br>
		 <input type="checkbox" name="skills_group[]" value="Driver's license with car"> Driver's license with car</br>
		 <input type="checkbox" name="skills_group[]" value="Babysitting"> Babysitting</br>
		 <input type="checkbox" name="skills_group[]" value="Tutoring"> Tutoring</br>
		 <input type="checkbox" name="skills_group[]" value="Mentoring"> Mentoring</br>
		 <input type="checkbox" name="skills_group[]" value="Training/Speaking"> Training/Speaking</br>
		 <input type="checkbox" name="skills_group[]" value="Fundraising"> Fundraising</br>
		 <input type="checkbox" name="skills_group[]" placeholder="Other" value="Other"> Other: <input type="text" class="volunteer input-block-level" placeholder="Other skills"></br></br>

		<p>How much time do you have to give?</p>
		 <input type="checkbox" name="time_group[]" value="5 minutes"> 5 minutes</br>
		 <input type="checkbox" name="time_group[]" value="Event-specific (One-Off)"> Event-specific (One-Off)</br>
		 <input type="checkbox" name="time_group[]" value="Weekly"> Weekly</br>
		 <input type="checkbox" name="time_group[]" value="Monthly"> Monthly</br>
		 <input type="checkbox" name="time_group[]" value="Other"> Other: <input type="text" name="time_group[]" class="volunteer input-block-level" placeholder="Availability"></br></br>

		<p>When would you be available?</br>
		<small>(i.e. Sundays after noon)</small></p>
		<textarea row="5" name="available" class="volunteer input-block-level"></textarea>
		 
		<p>Anything else I should know when trying to match you with a volunteer opportunity?</p>
		<textarea row="5" name="anything_else" class="volunteer input-block-level"></textarea>
		<button class="volunteer-button">Submit</button>
		<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
	</form>
</div>