config/routes.rb
LGBTHomelessness::Application.routes.draw do

  root 'home#index'
  get 'about' => "home#about"
  get 'who_are_you' => "home#who"
  get 'volunteer' => "home#volunteer"
  get 'contact' => "home#contact"
  get 'calendar' => "home#calendar"
  get 'results' => "home#result"
  post 'contact' => "contact#create"
  post 'volunteer' => 'volunteer#create'
  get 'volunteers' => "volunteer#index"
  get 'org_list' => "home#org_list"
  get 'wish_lists' => "home#wish_lists"
  get 'donate_money' => "home#donate_money"
  get 'give_help' => "home#give_help"
  get 'mobile' => "home#mobile"
  post 'sms_request' => "sms#received"
  get  'sms_test'    => "sms#test"

  resources :organizations do
      resources :programs
  end

  resources :programs

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LGBTHomelessness - <%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<header class="navbar col-lg-12">
		<%= link_to(image_tag("LGBTHomelessness_Logo.png", :class => "logo", :alt => "logo", :title => "LGBT Homelessness"), "/") %>
		<nav>
			<ul>
				<li><%= link_to "Search Resources", who_are_you_path %></li>
        <LI><%= link_to "Resources List", org_list_path %></li>
				<li><%= link_to "Give Help", give_help_path %></li>
        <li><%= link_to "Services Calendar", calendar_path %></li>
			</ul>
      <span class="sub-nav">
        <%= link_to "About", about_path %> | <%= link_to "Contact Us", contact_path %>
        &nbsp;&nbsp;&nbsp;
        <a href="http://twitter.com/lgbtqhomeless" alt="Follow @LGBTQHomeless on Twitter!">
          <%= image_tag("twitter-icon.png", :alt => "Follow @LGBTQHomeless on Twitter",
                :title => "@LGBTQHomeless", :width => 51, :height => 51) %> </a>
        <A HREF="http://www.pinterest.com/lgbthomelessnes/">
          <%= image_tag("App-Pinterest-icon.png", :alt => "Follow LGBTHomelessness on Pinterest",
                :width => 51,:height => 51) %></a>
      </span>
		</nav>

	</header>

<%= yield %>

<footer class="col-lg-12">
  <small>While we do our best to confirm and maintain the accuracy of the information here, it is subject to change without notice. <br />When in doubt call ahead. If you notice a mistake in our information, please "flag as inaccurate" or use the <%= link_to "Contact Us", contact_path %> page to notify us.</small>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48750640-3', 'lgbthomelessness.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/layouts/application_mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LGBTHomelessness - <%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<header class="navbar col-lg-12">
		<%= link_to(image_tag("LGBTHomelessness_Logo.png", :class => "logo", :alt => "logo", :title => "LGBT Homelessness"), "/") %>
	</header>

<%= yield %>

<footer class="col-lg-12 blue-container">
  <small>While we do our best to confirm and maintain the accuracy of the information here, it is subject to change without notice. <br />When in doubt call ahead. If you notice a mistake in our information, please "flag as inaccurate" or use the <%= link_to "Contact Us", contact_path %> page to notify us.</small>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48750640-3', 'lgbthomelessness.com');
  ga('send', 'pageview');

</script>

</body>
</html>